version: "3.9"
services:
  backend:
    container_name: nodeapibackend
    build: ./
    image: nodeapibackend:v1
    ports:
      - "5002:5002"
    depends_on:
        - "postgresnode"
  postgresnode:
    environment:
      - POSTGRES_USER=express
      - POSTGRES_PASSWORD=express
      - POSTGRES_DB=express
    container_name: postgresnode
    image: "postgres:15.0"
    expose:
      - "5432"

#cd nodeapi
#docker compose build
#docker compose up --attach backend